const midterm_data_39 = [
    {
      id: 1,
      img:"/images/product-1.jpg",
      name:"high-back bench",
      price:"$9.99",
      category:'ikea',
    },
    {
      id: 2,
      img:"/images/product-2.jpg",
      name:"albany table",
      price:"79.99",
      category:'macros',
    },
    {
      id: 3,
      img:"/images/product-3.jpg",
      name:"accent chair",
      price:"$25.99",
      category:'caressa',
    },
    {
      id: 4,
      img:"/images/product-4.jpg",
      name:"wooden table",
      price:"$45.99",
      category:'ikea',
    },
    {
      id: 5,
      img:"/images/product-5.jpg",
      name:"dining table",
      price:"$6.99",
      category:'macros',
    },
    {
      id: 6,
      img:"/images/product-6.jpg",
      name:"sofa set",
      price:"$69.99",
      category:'caressa',
    },
    {
      id: 7,
      img:"/images/product-7.jpg",
      name:"modern bookshelf",
      price:"$8.99",
      category:'ikea',
    },
    {
      id: 8,
      img:"/images/product-8.jpg",
      name:"emperor bed",
      price:"$21.99",
      category:'macros',
    },
    {
      id: 9,
      img:"/images/product-9.jpg",
      name:"utopia sofa",
      price:"$39.95",
      category:'caressa',
    },
    {
      id: 10,
      img:"/images/product-10.jpg",
      name:"entertainment center",
      price:"$29.98",
      category:'ikea',
    },
    {
      id: 10,
      img:"/images/product-11.jpg",
      name:"albany sectional",
      price:"$10.99",
      category:'macros',
    },
    {
      id: 12,
      img:"/images/product-12.jpg",
      name:"leather sofa",
      price:"$9.99",
      category:'caressa',
    },
  ];
  export default midterm_data_39;
  